# -*- coding: utf-8 -*-
"""Comparar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xi63kU2FO7I-MKEjUt1bupXLAZellSGJ
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

def cargarImagen():
    # Cargar la imagen
    filename = input("Ingrese el nombre del archivo de imagen (incluyendo la extensión): ")
    img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)

    # Mostrar la imagen original
    plt.figure(figsize=(12, 8))
    plt.subplot(2, 2, 1)
    plt.imshow(img, cmap='gray')
    plt.title('Imagen Original')

    # Detección de bordes usando operaciones morfológicas
    se = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    img_dilated = cv2.dilate(img, se)
    bordes_morph = cv2.absdiff(img_dilated, img)

    plt.subplot(2, 2, 2)
    plt.imshow(bordes_morph, cmap='gray')
    plt.title('Bordes Morfológicos')

    # Detección de bordes usando Sobel
    bordes_sobel = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3) + cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
    bordes_sobel = np.uint8(np.absolute(bordes_sobel))

    plt.subplot(2, 2, 3)
    plt.imshow(bordes_sobel, cmap='gray')
    plt.title('Bordes Sobel')

    # Detección de bordes usando Canny
    bordes_canny = cv2.Canny(img, 100, 200)

    plt.subplot(2, 2, 4)
    plt.imshow(bordes_canny, cmap='gray')
    plt.title('Bordes Canny')

    # Mostrar todas las imágenes
    plt.show()

# Llamar a la función para cargar la imagen
cargarImagen()